# Generated by Django 2.2 on 2020-06-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=25)),
                ('timeStemp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
